# Generated by Django 2.0.8 on 2018-08-15 21:51

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180815_2151'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Coach Category',
                'verbose_name_plural': 'Coach Categories',
            },
        ),
        migrations.AddField(
            model_name='coachpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
    ]
