# Generated by Django 2.0.8 on 2018-08-15 21:52

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_auto_20180815_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='coach.CoachCategory'),
        ),
    ]
